name: fldome
description: A new Flutter project.

publish_to: 'none'

version: 0.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dart_vlc: ^0.1.8
  device_preview: ^0.7.4
  extended_nested_scroll_view: ^5.0.0
  get: ^4.3.8
  suit: 1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true
